config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  delete 'logout' => 'sessions#destroy'

  resources :users do
    resources :share, :only => [:create,:destroy,:show]
  end

  resources :user_admin
  resources :materials
  get 'new_pdf' => 'materials#new_pdf'
  post 'new_pdf' => 'materials#create_pdf'

end

app/models/material.rb
class Material < ActiveRecord::Base
  has_and_belongs_to_many :users

  before_validation :clean_body

  validates :title,
    presence: true

  validates :body,
    presence: true

  protected

  def clean_body
    self.body = Sanitize.fragment(self.body,
     :elements => ['b', 'i', 'u', 'p', 'span', 'strong', 'strike', 'em', 'ol', 'li', 'ul', 'a', 'img', 'style'],
     :attributes => {'div' => ['style'], 'a' => ['href']},
     :css => { :properties => ['color']
    })
  end

end

app/models/materials_users.rb
class MaterialsUsers < ActiveRecord::Base
  belongs_to :material
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_and_belongs_to_many :materials

  validates_presence_of :password, :on => :create

  validates :name,
    presence: true

  validates :email,
    presence: true,
    uniqueness: {case_sensitive: false},
    email: true

  validates :password,
    presence: true,
    confirmation: true,
    length: { minimum: 6 }

  validates :phone, presence: true

  def self.authenticate email,password
    User.find_by_email(email).try(:authenticate, password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :current_user

  private

  def is_admin?
    is_authenticated?
    unless current_user.kind == "admin"
      flash[:warning] = "Oops. You need to be an admin to visit that page."
      redirect_to user_path session[:user_id]
    end
  end

  def is_authenticated?
    unless current_user
      flash[:warning] = "Oops. You need to log in to do that."
      redirect_to root_path
    end
  end

  def current_user
    @current_user ||= User.find_by_id(session[ :user_id ] )
    gon.current_user = @current_user
  end

  def get_material_by_id id
    Material.find(id)
  end

  def delete_association user,association
    if association
      user.materials.delete(association)
    end
  end

end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController

  def index
    is_admin?
    @all_materials = add_user_info get_all_materials
  end

  def show
    is_authenticated?
    @material = get_material_by_id params[:id]
    @current_user = current_user
  end

  def new
    is_admin?
    @new_material = Material.new
  end

  def new_pdf
    is_admin?
    @new_material = Material.new
  end

  def create
    is_admin?
    created_material = Material.create( material_params )
    redirect_to material_path created_material[:id]
  end

  def edit
    is_admin?
    @material = Material.find( params[:id] )
  end

  def update
    is_admin?
    Material.find( params[:id] ).update( material_params )
    redirect_to material_path params[:id]
  end

  def destroy
    is_admin
    Material.delete( params[:id] )
    flash[:success] = "Material was successfully deleted."
    redirect_to materials_path
  end

  private

  def material_params
    params.require(:material).permit(:title, :body, :kind)
  end

  def get_all_materials
    Material.all
  end

  def add_user_info materials
    material_info = []
    materials.each do |m|
      users = []
      m.users.each do |u|
        users.push({id: u[:id], name: u[:name] + u[:lastname] })
      end
      material_info.push({material: m, users: users })
    end
    material_info
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.authenticate(params[:user][:email],params[:user][:password])

    if @user
      session[:user_id] = @user.id
      flash[:success] = "Login Successful"
      if @user.kind == 'admin'
        redirect_to user_admin_index_path
      else
        redirect_to user_path session[:user_id]
      end
    else
      flash[:danger] = "Credentials Invalid"
      redirect_to root_path
    end

  end

  def destroy
    session[:user_id] = nil
    flash[:info] = "You are now logged out. Come back soon."
    redirect_to root_path
  end

  private

end

app/controllers/share_controller.rb
class ShareController < ApplicationController

  def show
    is_admin?
    @material = get_material_by_id params[:id]
    @current_associations = @material.users
    @non_associations = get_all_non_associated_users @current_associations
  end

  def create
    is_admin?
    User.find(params[:user_id]).materials << Material.find(params[:material_id])
    redirect_to "/users/#{current_user.id}/share/#{params[:material_id]}"
  end

  def destroy
    is_admin?
    user = User.find(params[:user_id])
    association = user.materials.find(params[:id])
    delete_association user,association

    redirect_to "/users/#{current_user.id}/share/#{params[:id]}"
  end

  private

  def get_all_non_associated_users associations
    users = []
    User.find_each do | u |
      if associations.index(u) == nil
        users.push(u)
      end
    end
    users
  end

end

app/controllers/user_admin_controller.rb
class UserAdminController < ApplicationController

  def index
    is_admin?
    @all_users = User.all
  end

  def show
    is_admin?
    @user = User.find(params[:id])
    @user_materials = @user.materials
    @all_materials = get_all_non_associated_materials @user_materials
  end

  def destroy
    is_admin?
    user = User.find(params[:id])
    association = user.materials.find(params[:material_id])
    delete_association user,association
    redirect_to user_admin_path params[:id]
  end

  def create
    is_admin?
    User.find(params[:user_id]).materials << Material.find(params[:material_id])
    redirect_to "/user_admin/#{params[:user_id]}/"
  end

  private

  def get_all_non_associated_materials associations
    materials = []
    Material.find_each do | m |
      if associations.index(m) == nil
        materials.push(m)
      end
    end
    materials
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    user_create_validation
  end

  def show
    is_authenticated?
    @user_materials = current_user.materials
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :name, :lastname, :phone)
  end

  def user_create_validation
    if @user['id'].nil?
      flash[:danger] = "Error trying to create new login"
      redirect_to root_path
    elsif current_user.kind == "admin"
      flash[:success] = "New client account successfully created!."
      redirect_to user_admin_path @user.id
    else
      flash[:success] = "Account Creation Successful! You may log in now."
      redirect_to root_path
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if current_user
      if current_user.kind == 'admin'
        redirect_to user_admin_index_path
      elsif current_user
        redirect_to user_path session[:user_id]
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/share_helper.rb
module ShareHelper
end

app/helpers/user_admin_helper.rb
module UserAdminHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |k,v| %>
  <div class="alert alert-<%= k %>">
    <%= v %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Empower Your Life - Supplimental Materials</title>
  <!-- Latest compiled and minified CSS & JS -->
  <!-- <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"> -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.5/cerulean/bootstrap.min.css">

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= include_gon(:init => true) %>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Empower Your Life - Supplemental Materials</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">

    <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <% if @current_user %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @current_user.name %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
            <% if @current_user[:kind] == 'admin' %>
              <li><%= link_to "Add New Materials", new_material_path %></li>
              <li><%= link_to "Add New PDF", new_pdf_path %></li>
              <li><%= link_to "Materials", materials_path %></li>
              <li><%= link_to "Users", user_admin_index_path %></li>
            <% end %>
            <% if @current_user[:kind] != 'admin' %>
              <li><%= link_to "My Materials", user_path %></li>
            <% end %>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log out", logout_path %></li>
          <% end %>
          </ul>
        </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>
<%= image_tag("banner.jpg", width: "350") %>
<%= render 'layouts/flash' %>
<%= yield %>

</body>
</html>

app/views/materials/edit.html.erb
<% if @material.kind == "article" %>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h2>Edit material</h2>
      <%= bootstrap_form_for(@material) do |f| %>
        <%= f.text_field :title %>
        <%= f.text_area :body %>
        <%= f.hidden_field :kind, value: "article" %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
  <script>
    $(function() {
        $.FroalaEditor.DEFAULTS.key = '9xsoovgqA-9jsudc1lnxbaccI1qA-16y==';
        $('#material_body').editable({inlineMode: false});
    });
  </script>
<% elsif @material.kind == "pdf" %>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h2>Edit material</h2>
      <%= bootstrap_form_for(@material) do |f| %>
        <%= f.text_field :title %>
        <%= f.text_field :body %>
        <%= f.hidden_field :kind, value: "pdf" %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/materials/index.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <span class="pull-right"><a href="/new_pdf"><span class="label label-primary">Add new pdf</span></a></span>
    <span class="pull-right"><a href="/materials/new"><span class="label label-primary">Add new material</span></a></span>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2>All materials</h2>
      <table class="table table-striped">
        <tr>
          <th>Share</th>
          <th>ID</th>
          <th>Title</th>
          <th>Type</th>
          <th>Delete?</th>
        </tr>
        <% @all_materials.each do |m| %>
          <tr>
            <td>
              <a href="/users/<%= :current_user %>/share/<%= m[:material][:id] %>">Manage Access</a>
            </td>
            <td><%= m[:material][:id] %></td>
            <td>
              <a href="/materials/<%= m[:material][:id] %>"><strong><%= m[:material][:title] %></strong></a> -
              <a href="/materials/<%= m[:material][:id] %>/edit">Edit</a>
            </td>
            <td><%= m[:material][:kind] %></td>
            <td>
              <!-- FIX DELETE FORM -->
              <form accept-charset="UTF-8" action="/materials/<%= m[:material][:id] %>" method="destroy">
                <button type="button" class="close" aria-label="Delete">
                  <span aria-hidden="true">&times;</span>
                </button>
              </form>
            </td>
          </tr>
        <% end %>
      </table>
  </div>
</div>
<%= %>

app/views/materials/new.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2>Add new materials</h2>
    <%= bootstrap_form_for(@new_material) do |f| %>
      <%= f.text_field :title, placeholder: "Enter Title" %>
      <textarea id="material_body" name="material[body]"></textarea>
      <%= f.hidden_field :kind, value: "article" %>
      <%= f.submit %>
    <% end %>
  </div>
</div>
<script>
  $(function() {
      $.FroalaEditor.DEFAULTS.key = '9xsoovgqA-9jsudc1lnxbaccI1qA-16y==';
      $('#material_body').editable({inlineMode: false});
  });
</script>

app/views/materials/new_pdf.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2>Add new materials</h2>
    <%= bootstrap_form_for(@new_material) do |f| %>
      <%= f.text_field :title, placeholder: "Enter Title" %>
      <%= f.text_field :body, placeholder: "Enter URL to PDF file" %>
      <%= f.hidden_field :kind, value: "pdf" %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/materials/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>
      <%= @material.title %></h1>
      <% if @current_user[:kind] == 'admin' %>
        <p>
          <%= link_to "Edit", edit_material_path %> |
          <%= link_to "Manage Access", user_share_path( @current_user.id,@material.id )%> |
          <%= link_to "View All Materials", materials_path %>
        </p>
      <% end %>

    <span class="label label-default"><%= @material.kind %></span>
    <div class="row">
    <hr>
      <div class="froala-view no-select">
        <% if @material.kind == "article" %>
          <%= raw @material.body %>
        <% elsif @material.kind == "pdf" %>
          <p><a href="<%= @material.body %>" target="_blank">Download PDF</a></p>
          <object data="<%= @material.body %>" type="application/pdf" width="100%" height="1000px">
            <p>It appears you don't have a PDF plugin for this browser.
              No biggie... you can <a href="<%= @material.body %>">click here to
              download the PDF file.</a>
            </p>
          </object>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/share/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h2>
      Share <%= @material.title %>
    </h2>
      <% if @current_user[:kind] == 'admin' %>
       <p><%= link_to "Edit Material", edit_material_path %> |
       <%= link_to "View All Materials", materials_path %></p>
      <% end %>
    <div class="row">
    <hr>
      <div class="col-md-6">
        <h3>Not Shared With</h3>
        <table class="table table-striped">
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Share?</th>
          </tr>
          <% @non_associations.each do |u| %>
            <tr>
              <td><%= u.id %></td>
              <td><%= u.name %> <%= u.lastname %></td>
              <td><%= u.email %></td>
              <td>
                <%= bootstrap_form_tag url: "/users/#{u.id}/share/" do |f| %>
                  <%= f.hidden_field :material_id, value: "#{@material.id}"%>
                  <%= f.submit "Share", class: "btn btn-success btn-sm"%>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
      <div class="col-md-6">
        <h3>Shared With</h3>
        <table class="table table-striped">
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Unshare?</th>
          </tr>
          <% @current_associations.each do |u| %>
            <tr>
              <td><%= u.id %></td>
              <td><%= u.name %> <%= u.lastname %></td>
              <td><%= u.email %></td>
              <td>
                <%= bootstrap_form_tag url: "/users/#{u.id}/share/#{@material.id}", method: "delete" do |f| %>
                  <%= f.submit "Unshare", class: "btn btn-danger btn-sm"%>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/user_admin/index.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <span class="pull-right"><a href="/users/new"><span class="label label-primary">Add new user</span></a></span>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
  <h2>All Users</h2>
    <table class="table table-striped">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Phone #</th>
        <th>Delete? (not yet implemented)</th>
      </tr>
      <% @all_users.each do |u| %>
        <tr>
          <td><%= u.id %></td>
          <td><a href="/user_admin/<%= u.id %>"><%= u.name %> <%= u.lastname %></a></td>
          <td><%= u.email %></td>
          <td><%= u.phone %></td>
          <td>delete</td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/user_admin/show.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="row">
      <h2>Manage <%= @user.name %> <%= @user.lastname %></h2>
      <span class="pull-right"><a href="/users/<%= @user.id %>/edit"><span class="label label-primary">Edit User Info</span></a> (not yet working)</span>
      <hr>
      <h4>User info:</h4>
      <table class="table table-striped">
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Email</th>
          <th>Phone</th>
        </tr>
        <tr>
          <td><%= @user.id %></td>
          <td><%= @user.name %> <%= @user.lastname %></td>
          <td><%= @user.email %></td>
          <td><%= @user.phone %></td>
        </tr>
      </table>
    </div>
    <hr>
    <div class="row">
    <h3>Manage Materials Access</h3>
        <h4>Materials Shared With User</h4>
        <table class="table table-striped">
        <tr>
          <th>ID</th>
          <th>Title</th>
          <th>Type</th>
          <th>Remove Access?</th>
        </tr>
        <% @user_materials.each do |m| %>
          <tr>
            <td><%= m[:id] %></td>
            <td>
              <a href="/materials/<%= m[:id] %>"><strong><%= m[:title] %></strong></a> -
              <a href="/materials/<%= m[:id] %>/edit">Edit</a>
            </td>
            <td><%= m[:kind] %></td>
            <td>
              <%= bootstrap_form_tag url: "/user_admin/#{@user.id}", method: "delete" do |f| %>
                <%= f.hidden_field :material_id, value: "#{m.id}"%>
                <%= f.submit "Unshare", class: "btn btn-danger btn-sm"%>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="row">
      <h4>Materials Not Shared With User</h4>
      <table class="table table-striped">
        <tr>
          <th>ID</th>
          <th>Title</th>
          <th>Type</th>
          <th>Give Access?</th>
        </tr>
        <% @all_materials.each do |m| %>
          <tr>
            <td><%= m[:id] %></td>
            <td>
              <a href="/materials/<%= m[:id] %>"><strong><%= m[:title] %></strong></a> -
              <a href="/materials/<%= m[:id] %>/edit">Edit</a>
            </td>
            <td><%= m[:kind] %></td>
            <td>
              <%= bootstrap_form_tag url: "/user_admin/", method: "post" do |f| %>
                <%= f.hidden_field :material_id, value: "#{m.id}"%>
                <%= f.hidden_field :user_id, value: "#{@user.id}"%>
                <%= f.submit "Share", class: "btn btn-primary btn-sm"%>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2>New Client?</h2>
    <p>Sign up now for quick and easy access to your supplemental materials.</p>
    <%= bootstrap_form_for(@user) do |f| %>
      <%= f.text_field :name, placeholder: "Enter first name", icon: "user" %>
      <%= f.text_field :lastname, placeholder: "Enter last name", icon: "user" %>
      <%= f.email_field :email, placeholder: "Enter email", icon: "envelope" %>
      <%= f.phone_field :phone, placeholder: "Enter phone number", icon: "phone" %>
      <%= f.password_field :password, placeholder: "Enter Your Password", icon: 'lock', help: "Must be at least 6 characters long" %>
      <%= f.password_field :password_confirmation, placeholder: "Confirm Password", icon: 'lock' %>
      <div class="row">
        <p>By signing up you agree not to download, distribute, print, or share any of the content contained on this site without expressly written permission from the Empower Your Life Hypnotherapy. Thanks for respecting our content.</p>
      </div>
      <%= f.submit "Sign Up" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-2">
    <h2>Your current materials</h2>
      <ul class="list-group">
    <% @user_materials.each do |m| %>
        <li class="list-group-item"><a href="/materials/<%= m.id %>"><%= m.title %></a></li>
    <% end %>
      </ul>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2>Sign in</h2>
    <%= bootstrap_form_for :user, url: login_path do |f| %>
      <%= f.email_field :email, placeholder: "Enter email", icon: "envelope" %>
      <%= f.password_field :password, placeholder: "Enter Your Password", icon: 'lock' %>
      <%= f.submit "Log In" %>
    <% end %>
    <br>
    <%= link_to "New Client? Create an account.", new_user_path %>
  </div>
</div>